#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18047
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("org.vocaluxe.app.Resource", IsApplication=true)]

namespace org.vocaluxe.app
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int btConnect = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int btDiscover = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int btSendAvatar = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int btSendProfile = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int tbIP = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int tbPassword = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int tbPlayerName = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int textView3 = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int button_connect = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int button_disconnect = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int button_send_avatar = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int button_send_profile = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int ip_address = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int message_connected = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int message_disconnected = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int message_nok = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int message_ok = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int password = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int text_ip_address = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int text_password = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int text_player_name = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
