on:
  workflow_call:
    inputs:
      tag_name:
        description: "The tag name for the release"
        required: true
        type: string
      prerelease:
        description: "Indicates if the release is a pre-release"
        required: true
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        platform: [x86, x64]
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          # Version of Visual Studio to search; defaults to latest if not specified
          vs-version: latest # optional
          # The preferred processor architecture of MSBuild. Can be either "x86", "x64", or "arm64". "x64" is only available from Visual Studio version 17.0 and later.
          msbuild-architecture: ${{ matrix.platform }} # optional, default is x86

      - name: Setup Nuget
        uses: NuGet/setup-nuget@v2.0.0

      - name: Restore Nuget Packages
        run: nuget restore Vocaluxe.sln

      - name: Build solution
        env:
          VOCALUXE_VERSION: ${{ inputs.tag_name != 'Nightly' && inputs.tag_name || '' }}
        run: msbuild Vocaluxe.sln /p:Configuration=ReleaseWin /p:Platform="${{ matrix.platform }}"

      - name: Download theme videos
        run: |
          Invoke-WebRequest -Uri 'https://github.com/Vocaluxe/VocaluxeDependencies/raw/master/zips/themes/vocaluxe.themes.vocaluxe-2024.video-part1.zip' -OutFile 'vocaluxe.themes.vocaluxe-2024.video.zip'
          7z x '-aoa' '-oOutput/' './vocaluxe.themes.vocaluxe-2024.video.zip'
          Remove-Item './vocaluxe.themes.vocaluxe-2024.video.zip'

      - name: Run tests
        run: |
          nuget install NUnit.ConsoleRunner -Version 3.20.1 -OutputDirectory testrunner
          .\testrunner\NUnit.ConsoleRunner.3.20.1\tools\nunit3-console.exe ".\Tests\bin\Release\Tests.dll" --result=".\TestResult.xml"

      - name: Report test results
        uses: dorny/test-reporter@v2.1.1
        if: ${{ !cancelled() }}  
        with:
          reporter: dotnet-nunit 
          name: test-results
          path: TestResult.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Vocaluxe_Windows_${{ matrix.platform }}_${{ inputs.tag_name }}
          path: Output

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4.2.2

      - name: Delete Previous Release
        if: ${{ inputs.tag_name == 'Nightly' }}
        run: gh release delete Nightly --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: artifacts

      - name: Zip artifacts
        run: |
          for dir in . *; do
            if [ -d "$dir" ] && [ "$dir" != "." ] && [ "$dir" != ".." ]; then
              7z a -tzip "${dir}.zip" "${dir}/*"
            fi
          done
        working-directory: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          prerelease: ${{ inputs.prerelease }}
          tag_name: ${{ inputs.tag_name }}
          target_commitish: ${{ github.sha }}
          files: "artifacts/*.zip"
