name: Vocaluxe Nightly Builds

on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@4.2.2
        
      - name: test
        run: powershell dir
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          # Version of Visual Studio to search; defaults to latest if not specified
          vs-version: latest # optional
          # The preferred processor architecture of MSBuild. Can be either "x86", "x64", or "arm64". "x64" is only available from Visual Studio version 17.0 and later.
          msbuild-architecture: x64 # optional, default is x86
      - name: Setup Nuget
        uses: NuGet/setup-nuget@v2.0.0

      - name: Restore Nuget Packages
        run: nuget restore Vocaluxe.sln

      - name: Build solution
        run: msbuild Vocaluxe.sln /p:Configuration=ReleaseWin /p:Platform="x64"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Vocaluxe_Windows_x64_nightly
          path: Output
